In [1]:
from lifelines import CoxPHFitter
import pandas as pd
import numpy as np

In [2]:
df = pd.read_sas('whas500.sas7bdat')
df.head()

,ID,AGE,GENDER,HR,SYSBP,DIASBP,BMI,CVD,AFB,SHO,CHF,AV3,MIORD,MITYPE,YEAR,LOS,DSTAT,LENFOL,FSTAT
0,1.0,83.0,0.0,89.0,152.0,78.0,25.540510,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,5.0,0.0,2178.0,0.0
1,2.0,49.0,0.0,84.0,120.0,60.0,24.023979,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,5.0,0.0,2172.0,0.0
2,3.0,70.0,1.0,83.0,147.0,88.0,22.142900,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,5.0,0.0,2190.0,0.0
3,4.0,70.0,0.0,65.0,123.0,76.0,26.631870,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,10.0,0.0,297.0,1.0
4,5.0,70.0,0.0,63.0,135.0,85.0,24.412550,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,6.0,0.0,2131.0,0.0

In [3]:
df = df[["LENFOL", "AFB", "FSTAT"]]

In [4]:
df['LENFOL'] = df['LENFOL']/365.25
df['LENFOL'] = df['LENFOL'].round(decimals = 2)

In [5]:
df.head()

   LENFOL  AFB  FSTAT  Year
0    5.96  1.0    0.0  5.96
1    5.95  0.0    0.0  5.95
2    6.00  0.0    0.0  6.00
3    0.81  0.0    1.0  0.81
4    5.83  0.0    0.0  5.83

In [6]:
df.shape

(500, 4)

In [7]:
cph = CoxPHFitter(penalizer=0.1)

In [21]:
cph.fit(df, duration_col='LENFOL', event_col='FSTAT', formula='AFB', show_progress=True)

Iteration 1: norm_delta = 0.18792, step_size = 0.9500, log_lik = -1227.39936, newton_decrement = 4.34507, seconds_since_start = 0.0
Iteration 2: norm_delta = 0.01294, step_size = 0.9500, log_lik = -1223.44496, newton_decrement = 0.02674, seconds_since_start = 0.0
Iteration 3: norm_delta = 0.00076, step_size = 0.9500, log_lik = -1223.41816, newton_decrement = 0.00009, seconds_since_start = 0.0
Iteration 4: norm_delta = 0.00000, step_size = 1.0000, log_lik = -1223.41807, newton_decrement = 0.00000, seconds_since_start = 0.1
Convergence success after 4 iterations.

In [22]:
cph.print_summary()

<lifelines.CoxPHFitter: fitted with 500 total observations, 285 right-censored observations>
             duration col = 'LENFOL'
                event col = 'FSTAT'
                penalizer = 0.1
                 l1 ratio = 0.0
      baseline estimation = breslow
   number of observations = 500
number of events observed = 215
   partial log-likelihood = -1223.42
         time fit was run = 2023-08-23 11:45:28 UTC

---
            coef  exp(coef)   se(coef)   coef lower 95%   coef upper 95%  exp(coef) lower 95%  exp(coef) upper 95%
covariate
AFB         0.46       1.58       0.16             0.15             0.76                 1.16                 2.14

            cmp to    z      p   -log2(p)
covariate
AFB           0.00 2.93 <0.005       8.21
---
Concordance = 0.54
Partial AIC = 2448.84
log-likelihood ratio test = 7.96 on 1 df
-log2(p) of ll-ratio test = 7.71